---
- name: Crear Carpeta
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: Crear la carpeta en C:\Users\Administrator
      win_file:
        path: C:\Users\nuevo
        state: directory
      become_user: Administrator
