---
- name: Instalar IIS y ASP.NET
  hosts: localhost
  become: yes
  tasks:
    - name: Instalar IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Instalar ASP.NET
      win_feature:
        name: Web-Asp-Net45
        state: present
