---
- name: Instalar IIS y ASP.NET
  hosts: all
  become: yes
  gather_facts: no
  become_method: runas
  tasks:
    - name: Crear directorio temporal
      file:
        path: C:\ansible_tmp
        state: directory
        become_user: Administrator
    - name: Definir la ubicación del directorio temporal
      set_fact:
        ansible_temp_dir: C:\\ansible_tmp
        become_user: Administrator
    - name: Instalar IIS
      win_feature:
        name: Web-Server
        state: present
        become_user: Administrator
    - name: Instalar ASP.NET
      win_feature:
        name: Web-Asp-Net45
        state: present
        become_user: Administrator
