---
- name: Crear Carpeta
  hosts: localhost
  become: yes
  gather_facts: no
  become_user: Administrator
  tasks:
    - name: Crear la carpeta en C:\Users\Administrator
      win_file:
        path: C:\Users\Administrator\nueva_carpeta
        state: directory


