---
- name: Crear Carpeta
  hosts: all
  become_method: runas
  become: yes
  become_user: Administrator
  tasks:
  - name: Create directory structure
    ansible.windows.win_file:
      path: C:\ansibledir
      state: directory
